import { NodeDatas, EdgeDatas } from "../types/GraphData";

export const nodeDatas: NodeDatas = {
    1: {
        A: {
            id: "A",
            x: 50,
            y: 50,
        },
        B: {
            id: "B",
            x: 150,
            y: 50,
        },
        C: {
            id: "C",
            x: 250,
            y: 50,
        },
        D: {
            id: "D",
            x: 200,
            y: 125,
        },
        E: {
            id: "E",
            x: 300,
            y: 125,
        },
        F: {
            id: "F",
            x: 250,
            y: 200,
        },
        G: {
            id: "G",
            x: 150,
            y: 200,
        },
    },
    2: {
        A: {
            id: "A",
            x: 30,
            y: 150,
        },
        B: {
            id: "B",
            x: 175,
            y: 150,
        },
        C: {
            id: "C",
            x: 300,
            y: 100,
        },
        D: {
            id: "D",
            x: 275,
            y: 275,
        },
        E: {
            id: "E",
            x: 75,
            y: 275,
        },
        F: {
            id: "F",
            x: 175,
            y: 50,
        },
    },
};

export const linkDatas: EdgeDatas = {
    1: {
        B_C: {
            v1: "B",
            v2: "C",
            x1: nodeDatas[1]["B"].x,
            y1: nodeDatas[1]["B"].y,
            x2: nodeDatas[1]["C"].x,
            y2: nodeDatas[1]["C"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 4,
        },
        C_E: {
            v1: "C",
            v2: "E",
            x1: nodeDatas[1]["C"].x,
            y1: nodeDatas[1]["C"].y,
            x2: nodeDatas[1]["E"].x,
            y2: nodeDatas[1]["E"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 2,
        },
        A_B: {
            v1: "A",
            v2: "B",
            x1: nodeDatas[1]["A"].x,
            y1: nodeDatas[1]["A"].y,
            x2: nodeDatas[1]["B"].x,
            y2: nodeDatas[1]["B"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 1,
        },
        B_D: {
            v1: "B",
            v2: "D",
            x1: nodeDatas[1]["B"].x,
            y1: nodeDatas[1]["B"].y,
            x2: nodeDatas[1]["D"].x,
            y2: nodeDatas[1]["D"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 8,
        },
        D_G: {
            v1: "D",
            v2: "G",
            x1: nodeDatas[1]["D"].x,
            y1: nodeDatas[1]["D"].y,
            x2: nodeDatas[1]["G"].x,
            y2: nodeDatas[1]["G"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 3,
        },
        D_E: {
            v1: "D",
            v2: "E",
            x1: nodeDatas[1]["D"].x,
            y1: nodeDatas[1]["D"].y,
            x2: nodeDatas[1]["E"].x,
            y2: nodeDatas[1]["E"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 1,
        },
        G_F: {
            v1: "G",
            v2: "F",
            x1: nodeDatas[1]["G"].x,
            y1: nodeDatas[1]["G"].y,
            x2: nodeDatas[1]["F"].x,
            y2: nodeDatas[1]["F"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 2,
        },
    },
    2: {
        A_B: {
            v1: "A",
            v2: "B",
            x1: nodeDatas[2]["A"].x,
            y1: nodeDatas[2]["A"].y,
            x2: nodeDatas[2]["B"].x,
            y2: nodeDatas[2]["B"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 1,
        },
        A_F: {
            v1: "A",
            v2: "F",
            x1: nodeDatas[2]["A"].x,
            y1: nodeDatas[2]["A"].y,
            x2: nodeDatas[2]["F"].x,
            y2: nodeDatas[2]["F"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 9,
        },
        A_E: {
            v1: "A",
            v2: "E",
            x1: nodeDatas[2]["A"].x,
            y1: nodeDatas[2]["A"].y,
            x2: nodeDatas[2]["E"].x,
            y2: nodeDatas[2]["E"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 3,
        },
        B_E: {
            v1: "B",
            v2: "E",
            x1: nodeDatas[2]["B"].x,
            y1: nodeDatas[2]["B"].y,
            x2: nodeDatas[2]["E"].x,
            y2: nodeDatas[2]["E"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 4,
        },
        B_D: {
            v1: "B",
            v2: "D",
            x1: nodeDatas[2]["B"].x,
            y1: nodeDatas[2]["B"].y,
            x2: nodeDatas[2]["D"].x,
            y2: nodeDatas[2]["D"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 5,
        },
        B_C: {
            v1: "B",
            v2: "C",
            x1: nodeDatas[2]["B"].x,
            y1: nodeDatas[2]["B"].y,
            x2: nodeDatas[2]["C"].x,
            y2: nodeDatas[2]["C"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 1,
        },
        C_F: {
            v1: "C",
            v2: "F",
            x1: nodeDatas[2]["C"].x,
            y1: nodeDatas[2]["C"].y,
            x2: nodeDatas[2]["F"].x,
            y2: nodeDatas[2]["F"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 2,
        },
        C_D: {
            v1: "C",
            v2: "D",
            x1: nodeDatas[2]["C"].x,
            y1: nodeDatas[2]["C"].y,
            x2: nodeDatas[2]["D"].x,
            y2: nodeDatas[2]["D"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 3,
        },
        E_D: {
            v1: "E",
            v2: "D",
            x1: nodeDatas[2]["E"].x,
            y1: nodeDatas[2]["E"].y,
            x2: nodeDatas[2]["D"].x,
            y2: nodeDatas[2]["D"].y,
            stroke: "#ccc",
            strokeWidth: "2",
            weight: 9,
        },
    },
};
