name: Build, Test and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        working-directory: game/frontend

      - name: Test with Vitest
        run: npm run test
        working-directory: game/frontend

      - name: Build
        run: npm run build
        working-directory: game/frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./game/frontend/dist  # Or your build output directory
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          commit_message: 'Deploy to GitHub Pages'
